#
#server:
#  port: 7101
#
#spring:
#  application:
#    name: microservice-config
#  security:
#    user:
#      name: admin
#      password: a
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/tph-lab/SpringCloud-Config.git
#          default-label: main        # 一定要配置，因为github升级后，已经没有 master 分支了， 而config server 默认是 master,  现在已经是 main
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://admin:a@localhost:7301/eureka
#  instance:
#    prefer-ip-address: true
#    instance-id: microservice-config1
server:
  port: 7201
spring:
  cloud:
    config:
      server:
        git:     #git服务器配置
          uri: https://github.com/tph-lab/SpringCloud-Config.git
          default-label: main


    bus:     # 开启bus消息总线    使其成为基于消息总线的配置中心     spring
      trace:
        enabled: true

    stream:
      kafka:
        binder:                                     #因为是远程的，需要进行域名映射（在hosts文件中）
          brokers: 120.26.177.155         #指明kafka的地址，默认是在本地，现在是远程访问 （9092可以不写，因为kafka默认就是9092）

  #  rabbitmq:
  #    host: localhost
  #    port: 5672    # RabbitMQ的监听端口
  #    username: zy  # 用户名
  #    password: a # 密码
  application:
    name: microservice-config-bus

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:a@localhost:7301/eureka
  instance:
    prefer-ip-address: true # 在地址栏上使用IP地址进行显示
    instance-id: microservice-config-bus
management:
  endpoints:
    web:
      exposure:
        include: "*"